#!/usr/bin/python3

def raise_exception_msg(message=""):
    print(f"{message}", end='')
    raise NameError
